- Makefile
- test/Makefile
- test/framework/Makefile
Remove theses messages:
ar: creating archive libprogram.a
ar: creating archive libunit.a
make[1]: Nothing to be done for `all'.
* Makefile message (STDOUT)
* ar message (STDERR)
> Makefile: remove useless messages

- test/Makefile
- test/framework/Makefile
- test/framework/inc/Stream.hpp
- test/framework/src/Stream.cpp
- test/inc/tests.hpp
- test/src/arguments/00_launcher.cpp
- test/src/arguments/02_test.cpp
* standard output
* standard error
Use `Stream` for checking `check_argc_number()`
Wikipedia: [TDD](https://en.wikipedia.org/wiki/Test-driven_development)
> Framework: catch streams

- Makefile
- inc/webserver.hpp
- src/main.cpp
- src/webserver.cpp
- keep the file `main.cpp` simple:
The `main.cpp` contains only the main function and nothing else.
- keep the `main()` function simple
The main checks the arguments and then calls the `webserver` function.
- `webserver.cpp`: change printed text: made a more verbose text
> update of the code structure

- inc/arguments.hpp
- src/arguments/check_argc_number.cpp
- src/main.cpp
- test/src/arguments/01_test.cpp
- test/src/arguments/02_test.cpp
move `check_argc_number()` into the namespace `arguments`
> Create the namespace arguments

- src/json/Value.cpp
- test/Makefile
- test/inc/tests.hpp
- test/src/Value/00_launcher.cpp
- test/src/Value/07_test.cpp
In `Value & Value::get(std::string const &key) const`:
* throw an exception if the key does not exist
* tdd: create a new test Value
> json::Value throw no existing key

- config.json
- inc/Response.hpp
- inc/serverTest.hpp
- src/http/Response.cpp
- src/serverTest/serverTest.cpp
- src/webserver.cpp
This feature just allows us to pass a simple json as an argument to the program and it will set the socket port to whatever  <"port" : value> is in the json file.
> Json server connection

- test/framework/src/Unit_test.cpp
```
int check_argc_number(int) : good argument number (2) : [OK]
int check_argc_number(int) : bad argument number (1) : [OK]
2/2 tests checked
class http parser : method GET : [OK]
1/1 tests checked
```
```
int check_argc_number(int) : good argument number (2) : [OK]
int check_argc_number(int) : bad argument number (1) : [OK]
2/2 tests checked
class http parser : method GET : [OK]
1/1 tests checked
```
> framework: better output format

- config.json
- inc/utils_json.hpp
- src/json/process_line.cpp
- src/json/read.cpp
- src/webserver.cpp
- test/Makefile
- test/inc/tests.hpp
- test/src/json/00_launcher.cpp
- test/src/json/03_test.cpp
- test/src/json/07_test.cpp
- test/src/json/08_test.cpp
- test/src/json/config_object00.json
- test/src/json/config_object01.json
```json
{
"foo.com": {
"port" : 6060,
"path" : "/path/of/foo.com"
},
"bar.org": {
"port" : 8080,
"path" : "/path/of/bar.org"
},
"php-cgi" : "/path/of/php-cgi"
}
```
* tdd: test object in the config file:
- json object 01
- json object 00
* improve `config.json`
* json:
- check last state
- add `END_OBJECT` as new state
the curly brace set this state to 1 `}`
if we arrive at the end of the object,
the function should return the object
- inverse state `OBJECT`, it is set to 1 just
after to meet `{`
> json parser: object in object

- inc/Request.hpp
- inc/Response.hpp
- src/http/Request.cpp
- src/http/Response.cpp
- test/website/is_dir.html
Add Response::check_if_is_dir() 
if the get request is a dir it sends a 404 not found default HTML page.
After we will make a &val object available in response it will send an HTML page
specified in the config.json or 404 not found if not specified.
> Check if dir

- src/Socket/Socket.cpp
- src/http/Request.cpp
- src/http/StatusCodes.cpp
```
miscellaneous improvement
```
```
* assign a value directly during the
instanciation
* reduce as much as possible the scope of
the variables
```
> misc: improve code

- test/website/errors/404.html
```
simple error page
```
```
resources:
https://httpcats.com/
```
> website: error 404 page

- Makefile
- config.json
- inc/Redirection.hpp
- src/http/Redirection.cpp
- test/Makefile
- test/inc/tests.hpp
- test/src/http-redirection/00_launcher.cpp
- test/src/http-redirection/01_test.cpp
- test/src/main.cpp
```
http: new class Redirection
```
```
this class take a json::t_oject at the
construction
method:
* is_redirection(string route, string & url)
if it's a rediction, return true else false
arguments:
- 1: the root
- 2: url string reference of the rediction,
set url in the function
```
https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections
> http: new class Redirection

- test/Makefile
- test/inc/tests.hpp
- test/src/http-redirection/01_test.cpp
- test/src/main.cpp
> fix: merge conflict

- config.json
- inc/Request.hpp
- inc/Response.hpp
- src/Socket/Socket.cpp
- src/http/Request.cpp
- src/http/Response.cpp
The branch implements the class Redirection.
Now you can add redirections in config.json.
Response::construct_header_string() is changed so it only adds headers that are not empty.
> Redirect implement

- Makefile
- python/script.py
- split function main
- launch a lot of request
* Intro: https://realpython.com/intro-to-python-threading/#starting-a-thread
* all documentations: https://docs.python.org/3/library/threading.html
> test: python multi thread

- src/json/check_config.cpp
- src/webserver.cpp
- json: check config refactor
- json: create check php()
- fix a "big" leak
> json: check configuration php-cgi executable

- Makefile
* make test
* sh setting script
* test-cpp
* test-python
* test-python
* make python 
* docker run
* test-cpp
* make test 
* run test/test
> makefile: new rule test-cpp

- test/src/check-json-config/01_test.cpp
Adapt the test
- add php-cgi from `setting.hpp`
> tdd: adapt `json::check_config()`

- src/json/process_line.cpp
- json: remove debug message
- json: call a `check_last_state()` before return
> json: call a check function

- docs/README.adoc
- docs/index.html
> docs: json resources

- inc/Response.hpp
- src/cgi/execve.cpp
- src/http/Response.cpp
This branch makes to connection between CGI and Response and send the string from the CGI to the client
> Cgi response connection

- config.json
- inc/cgi.hpp
- src/cgi/execve.cpp
- src/http/Response.cpp
- test/src/main.cpp
- test/src/php/00_launcher.cpp
- test/src/php/01_test.cpp
- test/src/php/02_test.cpp
NEW: Make little changes 
- Add theo's variable for the bin/php-cgi.
- Remove useless condition.
- Remove comments in php_handler
bisous
> Cgi change
